models:
  - label: "default"
    name: "OpenAI"

modules:
  - name: "BlogModule"
    signature: "dspygen.signatures.blog_article.BlogArticle"
    predictor: "Predict"
    model: "default"
    args:
      - name: "celebrity"
      - name: "news"

steps:
  - module: "BlogModule"
    args:
      celebrity: "Buckminster Fuller"
      news: "Sales of Critical Path off the charts!"

#
#ideas:
#  - "DG: add critic and quality checks"
#  - "AF: create 5 articles"
#  - "DG: Rank the N articles"
#  - "AF: Post the best article"
#  - "DG: Generate insight from stats and a report"
#  - "DG: Choose who should receive the email"
#  - "AF: Email insight"
#
#
#
